services:
  backend:
    ports:
      - 8000
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/conf/:/etc/nginx/ssl/:ro
      - static_volume:/app/staticfiles/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/www/:/var/www/certbot/:rw
      - ./nginx/certbot/conf/:/etc/letsencrypt/:rw

volumes:
  static_volume:
