version: '3.8'

services:
  web:
    ports:
      - 8000
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
