services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/staticfiles:/app/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.env
    restart: on-failure
